<?php


namespace app\index\controller;


use think\Controller;
use think\Session;

class BaseController extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if ($this->request->action() !== 'login' && !Session::has('admin')) {
            $this->redirect('/login',302);
        }
        if ($this->request->action() === 'login' && Session::has('admin')) {
            $this->redirect('/',302);
        }
    }

    protected function checkAuth()
    {
        $admin = Session::get('admin');
        if ($admin['level'] > 1) {
            $this->error('无权限，禁止操作');
        }
    }
}